backend:
  name: github
  repo: angelwanyama/ozzy-africa-website
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Website Pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "content/home.md"
        fields:
          - { label: "Hero Title", name: "hero_title", widget: "string" }
          - { label: "Hero Text", name: "hero_text", widget: "text" }
          - { label: "CTA Text", name: "cta_text", widget: "string" }

      - label: "About Page"
        name: "about"
        file: "content/about.md"
        fields:
          - { label: "Intro", name: "intro", widget: "text" }
          - { label: "Mission", name: "mission", widget: "text" }
          - { label: "Vision", name: "vision", widget: "text" }
